apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spesidaler-api
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: {{tier}}
        name: spesidaler
        databases:
          - name: spesidaler
            envVarPrefix: DATABASE
            users:
              - name: spesidaler-opprydding-dev
  strategy:
    type: RollingUpdate
  replicas:
    min: 2
    max: 12
  liveness:
    path: /isalive
  readiness:
    path: /isready
    periodSeconds: 1
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 1024Mi
  prometheus:
    path: /metrics
    enabled: true
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  accessPolicy:
    inbound:
      rules:
        - application: spesidaler-async
          permissions:
            roles:
              - "inntekter-for-beregning"
              - "inntektsendringer"
      outbound:
        - application: logging
          namespace: nais-system
  ingresses:
    {{#each ingresses }}
    - "{{this}}"
    {{/each}}
