apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spesidaler-opprydding-dev
  namespace: tbd
  labels:
    team: tbd
    db_policy_user: spesidalerbruker
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  startup:
    path: isready
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 9
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  kafka:
    pool: nav-dev
  prometheus:
    enabled: true
    path: /metrics
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
          name: tbd-dev-7ff9
        role: roles/cloudsql.client
  envFrom:
    - secret: google-sql-spesidaler-api-spesidaler-spesidaler-oppryd-7d72ab4a
  secureLogs:
    enabled: true
  env:
  - name: KAFKA_CONSUMER_GROUP_ID
    value: spesidaler-opprydding-dev-v1
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: DATABASE_REGION
    value: "europe-north1"
  - name: DATABASE_INSTANCE
    value: "spesidaler"


