[versions]
flyway = "13.3.0"
hikaricp = "7.1.0"
sasGradlePlugins = "20260807.0944"
tbd-libs = "20260820.1510"

[libraries]
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
cloud-sql-postgres-socket-factory = "com.google.cloud.sql:postgres-socket-factory:1.29.0"
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310" }
kotliquery = "com.github.seratch:kotliquery:1.9.1"
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
logback-classic = "ch.qos.logback:logback-classic:1.6.2"
logback-logstash-encoder = "net.logstash.logback:logstash-logback-encoder:9.0"
postgresql = "org.postgresql:postgresql:42.7.13"
rapids-and-rivers = "com.github.navikt:rapids-and-rivers:2026011411051768385145.e8ebad1177b4"
tbd-libs-azure = { module = "com.github.navikt.tbd-libs:azure-token-client-default", version.ref = "tbd-libs" }
tbd-libs-naisful-app = { module = "com.github.navikt.tbd-libs:naisful-app", version.ref = "tbd-libs" }
tbd-libs-sql-dsl = { module = "com.github.navikt.tbd-libs:sql-dsl", version.ref = "tbd-libs" }

jsonassert = "org.skyscreamer:jsonassert:1.5.3"
wiremock = "org.wiremock:wiremock-jetty12:3.13.2"
mockk = "io.mockk:mockk:1.14.11"
tbd-libs-mock-http-client = { module = "com.github.navikt.tbd-libs:mock-http-client", version.ref = "tbd-libs" }
tbd-libs-naisful-test-app = { module = "com.github.navikt.tbd-libs:naisful-test-app", version.ref = "tbd-libs" }
tbd-libs-postgres-testdatabaser = { module = "com.github.navikt.tbd-libs:postgres-testdatabaser", version.ref = "tbd-libs" }
tbd-libs-rapids-and-rivers-test = { module = "com.github.navikt.tbd-libs:rapids-and-rivers-test", version.ref = "tbd-libs" }
tbd-libs-signed-jwt-issuer-test = { module = "com.github.navikt.tbd-libs:signed-jwt-issuer-test", version.ref = "tbd-libs" }

[bundles]
logback = [
    "logback-classic",
    "logback-logstash-encoder",
]

[plugins]
sas-deployable = { id = "no.nav.helse.sas.sas-deployable", version.ref = "sasGradlePlugins" }
sas-root = { id = "no.nav.helse.sas.sas-root", version.ref = "sasGradlePlugins" }
