name: build async

on:
  push:
    branches:
      - main
    paths:
      - 'async/**'
      - '.github/workflows/async.yml'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'async.yml'
      - '.nais/async.yml'
      - '.nais/async-dev.json'
      - '.nais/async-prod.json'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.x'
          cache: 'gradle'
      - name: gradle
        run: ./gradlew :async:build
      - name: build docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: tbd
          dockerfile: Dockerfile
          image_suffix: async
          docker_context: async
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deployDev:
    name: deploy to dev
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/async.yml
          VARS: .nais/async-dev.json
          IMAGE: ${{ needs.build.outputs.image }}
  deployProd:
    name: deploy to prod
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/async.yml
          VARS: .nais/async-prod.json
          IMAGE: ${{ needs.build.outputs.image }}